/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  brandTagline?: string;
  copyrightText?: string;
  footerColumns?: Array<{
    columnTitle?: string;
    links?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  announcementText?: string;
  navLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type JournalInsider = {
  _id: string;
  _type: "journalInsider";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  summary?: string;
  slug?: Slug;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  publishedBy?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  closingNote?: string;
};

export type JournalArticle = {
  _id: string;
  _type: "journalArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  articles?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "journalInsider";
  }>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  priceINR?: number;
  comparePrice?: number;
  badge?: string;
  notes?: string;
  description?: string;
  longDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  weight?: string;
  size?: string;
  sku?: string;
  burnTime?: string;
  accentNotes?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  insiderInfo?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productInsider";
  };
  inStock?: boolean;
  featured?: boolean;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  seo?: {
    title?: string;
    description?: string;
  };
  orderRank?: number;
  collection?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  };
};

export type ProductInsider = {
  _id: string;
  _type: "productInsider";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  provenanceStory?: string;
  topNotes?: string;
  heartNotes?: string;
  baseNotes?: string;
  ingredientsList?: Array<string>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Divider = {
  _type: "divider";
  note?: string;
};

export type FaqList = {
  _type: "faqList";
  eyebrow?: string;
  headline?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: "faqItem";
    _key: string;
  }>;
};

export type TextBlock = {
  _type: "textBlock";
  eyebrow?: string;
  headline?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type RichText = {
  _type: "richText";
  eyebrow?: string;
  headline?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: {
    label?: string;
    url?: string;
  };
};

export type Cta = {
  _type: "cta";
  eyebrow?: string;
  headline?: string;
  description?: string;
  cta?: {
    label?: string;
    url?: string;
  };
  secondaryCta?: {
    label?: string;
    url?: string;
  };
  alignment?: "left" | "center";
};

export type Newsletter = {
  _type: "newsletter";
  eyebrow?: string;
  headline?: string;
  description?: string;
  ctaLabel?: string;
};

export type Testimonials = {
  _type: "testimonials";
  eyebrow?: string;
  headline?: string;
  testimonials?: Array<{
    author?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    rating?: number;
    _type: "testimonial";
    _key: string;
  }>;
};

export type Quote = {
  _type: "quote";
  text?: string;
  author?: string;
  role?: string;
};

export type JournalGrid = {
  _type: "journalGrid";
  eyebrow?: string;
  headline?: string;
  description?: string;
  articles?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "journalInsider";
  }>;
  cta?: {
    label?: string;
    url?: string;
  };
};

export type EditorialImage = {
  _type: "editorialImage";
  eyebrow?: string;
  headline?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  caption?: string;
};

export type ImageText = {
  _type: "imageText";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  eyebrow?: string;
  headline?: string;
  description?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cta?: {
    label?: string;
    url?: string;
  };
  imagePosition?: "left" | "right";
};

export type CollectionGrid = {
  _type: "collectionGrid";
  eyebrow?: string;
  headline?: string;
  description?: string;
  collections?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "collection";
  }>;
  layout?: "2" | "3";
};

export type ProductGrid = {
  _type: "productGrid";
  eyebrow?: string;
  headline?: string;
  description?: string;
  collection?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  };
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  count?: number;
  layout?: "2" | "3" | "4";
  cta?: {
    label?: string;
    url?: string;
  };
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  orderRank?: number;
};

export type FeaturedProducts = {
  _type: "featuredProducts";
  eyebrow?: string;
  headline?: string;
  description?: string;
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  cta?: {
    label?: string;
    url?: string;
  };
};

export type Manifesto = {
  _type: "manifesto";
  eyebrow?: string;
  headline?: string;
  quote?: string;
  metrics?: Array<{
    value?: string;
    label?: string;
    description?: string;
    _type: "metric";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  headline?: string;
  tagline?: string;
  subtext?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cta?: {
    label?: string;
    url?: string;
  };
  alignment?: "left" | "center";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageType?: "home" | "shop" | "journal" | "about" | "contact" | "faq" | "concierge" | "privacy" | "terms" | "shipping" | "returns";
  sections?: Array<{
    _key: string;
  } & Hero | {
    _key: string;
  } & Manifesto | {
    _key: string;
  } & FeaturedProducts | {
    _key: string;
  } & ProductGrid | {
    _key: string;
  } & CollectionGrid | {
    _key: string;
  } & ImageText | {
    _key: string;
  } & EditorialImage | {
    _key: string;
  } & JournalGrid | {
    _key: string;
  } & Quote | {
    _key: string;
  } & Testimonials | {
    _key: string;
  } & Newsletter | {
    _key: string;
  } & Cta | {
    _key: string;
  } & RichText | {
    _key: string;
  } & TextBlock | {
    _key: string;
  } & FaqList | {
    _key: string;
  } & Divider>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Footer | Navbar | JournalInsider | JournalArticle | Product | ProductInsider | Divider | FaqList | TextBlock | RichText | Cta | Newsletter | Testimonials | Quote | JournalGrid | EditorialImage | ImageText | CollectionGrid | ProductGrid | Collection | FeaturedProducts | Manifesto | Hero | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../sanity/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    pageType,      "sections": sections[] {    ...,    _type,    _key,    "backgroundImageUrl": backgroundImage.asset->url,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, backgroundImage.alt),    "products": products[]-> {        _id,  name,  slug,  price,  priceINR,  badge,  notes,  description,  weight,  burnTime,  inStock,  "image": image.asset-> {    _id,    url  },  "imageAlt": image.alt    },    "articles": articles[]-> {      _id,      title,      slug,      publishedAt,      "summary": coalesce(summary, description),      "publishedBy": coalesce(publishedBy, author),      coverImage    },    "collections": collections[]-> {      _id,      name,      slug,      description,      image    },    "collection": collection-> {      _id,      name,      slug,      "products": products[]-> {          _id,  name,  slug,  price,  priceINR,  badge,  notes,  description,  weight,  burnTime,  inStock,  "image": image.asset-> {    _id,    url  },  "imageAlt": image.alt      }    }  }  }
export type PAGE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  pageType: "about" | "concierge" | "contact" | "faq" | "home" | "journal" | "privacy" | "returns" | "shipping" | "shop" | "terms" | null;
  sections: Array<{
    _key: string;
    _type: "collectionGrid";
    eyebrow?: string;
    headline?: string;
    description?: string;
    collections: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }> | null;
    layout?: "2" | "3";
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collection: null;
  } | {
    _key: string;
    _type: "cta";
    eyebrow?: string;
    headline?: string;
    description?: string;
    cta?: {
      label?: string;
      url?: string;
    };
    secondaryCta?: {
      label?: string;
      url?: string;
    };
    alignment?: "center" | "left";
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "divider";
    note?: string;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "editorialImage";
    eyebrow?: string;
    headline?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    backgroundImageUrl: null;
    imageUrl: string | null;
    imageAlt: string | null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "faqList";
    eyebrow?: string;
    headline?: string;
    items?: Array<{
      question?: string;
      answer?: string;
      _type: "faqItem";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "featuredProducts";
    eyebrow?: string;
    headline?: string;
    description?: string;
    products: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      price: number | null;
      priceINR: number | null;
      badge: string | null;
      notes: string | null;
      description: string | null;
      weight: string | null;
      burnTime: string | null;
      inStock: boolean | null;
      image: {
        _id: string;
        url: string | null;
      } | null;
      imageAlt: string | null;
    }> | null;
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "hero";
    eyebrow?: string;
    headline?: string;
    tagline?: string;
    subtext?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    cta?: {
      label?: string;
      url?: string;
    };
    alignment?: "center" | "left";
    backgroundImageUrl: string | null;
    imageUrl: null;
    imageAlt: string | null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "imageText";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    eyebrow?: string;
    headline?: string;
    description?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    cta?: {
      label?: string;
      url?: string;
    };
    imagePosition?: "left" | "right";
    backgroundImageUrl: null;
    imageUrl: string | null;
    imageAlt: string | null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "journalGrid";
    eyebrow?: string;
    headline?: string;
    description?: string;
    articles: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
      publishedAt: string | null;
      summary: string | null;
      publishedBy: string | null;
      coverImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "manifesto";
    eyebrow?: string;
    headline?: string;
    quote?: string;
    metrics?: Array<{
      value?: string;
      label?: string;
      description?: string;
      _type: "metric";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "newsletter";
    eyebrow?: string;
    headline?: string;
    description?: string;
    ctaLabel?: string;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "productGrid";
    eyebrow?: string;
    headline?: string;
    description?: string;
    collection: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      products: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        price: number | null;
        priceINR: number | null;
        badge: string | null;
        notes: string | null;
        description: string | null;
        weight: string | null;
        burnTime: string | null;
        inStock: boolean | null;
        image: {
          _id: string;
          url: string | null;
        } | null;
        imageAlt: string | null;
      }> | null;
    } | null;
    products: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      price: number | null;
      priceINR: number | null;
      badge: string | null;
      notes: string | null;
      description: string | null;
      weight: string | null;
      burnTime: string | null;
      inStock: boolean | null;
      image: {
        _id: string;
        url: string | null;
      } | null;
      imageAlt: string | null;
    }> | null;
    count?: number;
    layout?: "2" | "3" | "4";
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    articles: null;
    collections: null;
  } | {
    _key: string;
    _type: "quote";
    text?: string;
    author?: string;
    role?: string;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "richText";
    eyebrow?: string;
    headline?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "testimonials";
    eyebrow?: string;
    headline?: string;
    testimonials?: Array<{
      author?: string;
      content?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      rating?: number;
      _type: "testimonial";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "textBlock";
    eyebrow?: string;
    headline?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  }> | null;
} | null;
// Variable: HOME_PAGE_DOC_QUERY
// Query: *[_type == "page" && pageType == "home"][0] {    _id,    title,    slug,    pageType,      "sections": sections[] {    ...,    _type,    _key,    "backgroundImageUrl": backgroundImage.asset->url,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, backgroundImage.alt),    "products": products[]-> {        _id,  name,  slug,  price,  priceINR,  badge,  notes,  description,  weight,  burnTime,  inStock,  "image": image.asset-> {    _id,    url  },  "imageAlt": image.alt    },    "articles": articles[]-> {      _id,      title,      slug,      publishedAt,      "summary": coalesce(summary, description),      "publishedBy": coalesce(publishedBy, author),      coverImage    },    "collections": collections[]-> {      _id,      name,      slug,      description,      image    },    "collection": collection-> {      _id,      name,      slug,      "products": products[]-> {          _id,  name,  slug,  price,  priceINR,  badge,  notes,  description,  weight,  burnTime,  inStock,  "image": image.asset-> {    _id,    url  },  "imageAlt": image.alt      }    }  }  }
export type HOME_PAGE_DOC_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  pageType: "home";
  sections: Array<{
    _key: string;
    _type: "collectionGrid";
    eyebrow?: string;
    headline?: string;
    description?: string;
    collections: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }> | null;
    layout?: "2" | "3";
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collection: null;
  } | {
    _key: string;
    _type: "cta";
    eyebrow?: string;
    headline?: string;
    description?: string;
    cta?: {
      label?: string;
      url?: string;
    };
    secondaryCta?: {
      label?: string;
      url?: string;
    };
    alignment?: "center" | "left";
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "divider";
    note?: string;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "editorialImage";
    eyebrow?: string;
    headline?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    backgroundImageUrl: null;
    imageUrl: string | null;
    imageAlt: string | null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "faqList";
    eyebrow?: string;
    headline?: string;
    items?: Array<{
      question?: string;
      answer?: string;
      _type: "faqItem";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "featuredProducts";
    eyebrow?: string;
    headline?: string;
    description?: string;
    products: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      price: number | null;
      priceINR: number | null;
      badge: string | null;
      notes: string | null;
      description: string | null;
      weight: string | null;
      burnTime: string | null;
      inStock: boolean | null;
      image: {
        _id: string;
        url: string | null;
      } | null;
      imageAlt: string | null;
    }> | null;
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "hero";
    eyebrow?: string;
    headline?: string;
    tagline?: string;
    subtext?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    cta?: {
      label?: string;
      url?: string;
    };
    alignment?: "center" | "left";
    backgroundImageUrl: string | null;
    imageUrl: null;
    imageAlt: string | null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "imageText";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    eyebrow?: string;
    headline?: string;
    description?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    cta?: {
      label?: string;
      url?: string;
    };
    imagePosition?: "left" | "right";
    backgroundImageUrl: null;
    imageUrl: string | null;
    imageAlt: string | null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "journalGrid";
    eyebrow?: string;
    headline?: string;
    description?: string;
    articles: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
      publishedAt: string | null;
      summary: string | null;
      publishedBy: string | null;
      coverImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "manifesto";
    eyebrow?: string;
    headline?: string;
    quote?: string;
    metrics?: Array<{
      value?: string;
      label?: string;
      description?: string;
      _type: "metric";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "newsletter";
    eyebrow?: string;
    headline?: string;
    description?: string;
    ctaLabel?: string;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "productGrid";
    eyebrow?: string;
    headline?: string;
    description?: string;
    collection: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      products: Array<{
        _id: string;
        name: string | null;
        slug: Slug | null;
        price: number | null;
        priceINR: number | null;
        badge: string | null;
        notes: string | null;
        description: string | null;
        weight: string | null;
        burnTime: string | null;
        inStock: boolean | null;
        image: {
          _id: string;
          url: string | null;
        } | null;
        imageAlt: string | null;
      }> | null;
    } | null;
    products: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      price: number | null;
      priceINR: number | null;
      badge: string | null;
      notes: string | null;
      description: string | null;
      weight: string | null;
      burnTime: string | null;
      inStock: boolean | null;
      image: {
        _id: string;
        url: string | null;
      } | null;
      imageAlt: string | null;
    }> | null;
    count?: number;
    layout?: "2" | "3" | "4";
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    articles: null;
    collections: null;
  } | {
    _key: string;
    _type: "quote";
    text?: string;
    author?: string;
    role?: string;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "richText";
    eyebrow?: string;
    headline?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    cta?: {
      label?: string;
      url?: string;
    };
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "testimonials";
    eyebrow?: string;
    headline?: string;
    testimonials?: Array<{
      author?: string;
      content?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      rating?: number;
      _type: "testimonial";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  } | {
    _key: string;
    _type: "textBlock";
    eyebrow?: string;
    headline?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    backgroundImageUrl: null;
    imageUrl: null;
    imageAlt: null;
    products: null;
    articles: null;
    collections: null;
    collection: null;
  }> | null;
} | null;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0] {    _id,    name,    slug,    price,    priceINR,    comparePrice,    badge,    notes,    description,    longDescription,    weight,    size,    sku,    burnTime,    accentNotes[],    inStock,    featured,    orderRank,    gallery[] {      asset-> {        _id,        url      },      caption    },    seo {      title,      description    },    "image": image.asset-> {      _id,      url    },    "imageAlt": image.alt,    collection -> {      name,      slug    },    insiderInfo -> {      title,      provenanceStory,      topNotes,      heartNotes,      baseNotes,      ingredientsList[],      gallery[] {        asset-> {          _id,          url        },        caption      }    }  }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  priceINR: number | null;
  comparePrice: number | null;
  badge: string | null;
  notes: string | null;
  description: string | null;
  longDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  weight: string | null;
  size: string | null;
  sku: string | null;
  burnTime: string | null;
  accentNotes: Array<string> | null;
  inStock: boolean | null;
  featured: boolean | null;
  orderRank: number | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
    caption: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  image: {
    _id: string;
    url: string | null;
  } | null;
  imageAlt: string | null;
  collection: {
    name: string | null;
    slug: Slug | null;
  } | null;
  insiderInfo: {
    title: string | null;
    provenanceStory: string | null;
    topNotes: string | null;
    heartNotes: string | null;
    baseNotes: string | null;
    ingredientsList: Array<string> | null;
    gallery: Array<{
      asset: {
        _id: string;
        url: string | null;
      } | null;
      caption: string | null;
    }> | null;
  } | null;
} | null;
// Variable: PRODUCTS_LIST_QUERY
// Query: *[_type == "product" && inStock == true] | order(orderRank asc, _createdAt asc) {    _id,    name,    slug,    price,    priceINR,    badge,    notes,    description,    weight,    burnTime,    "image": image.asset-> {      _id,      url    },    "imageAlt": image.alt,    inStock  }
export type PRODUCTS_LIST_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  priceINR: number | null;
  badge: string | null;
  notes: string | null;
  description: string | null;
  weight: string | null;
  burnTime: string | null;
  image: {
    _id: string;
    url: string | null;
  } | null;
  imageAlt: string | null;
  inStock: true;
}>;
// Variable: JOURNAL_PAGE_QUERY
// Query: *[_type == "journalArticle"][0] {    title,    tagline,    "articles": articles[]-> {        _id,  title,  slug,  publishedAt,  "summary": coalesce(summary, description),  "publishedBy": coalesce(publishedBy, author),  "coverImage": coverImage.asset-> {    _id,    url  }    }  }
export type JOURNAL_PAGE_QUERYResult = {
  title: string | null;
  tagline: string | null;
  articles: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    summary: string | null;
    publishedBy: string | null;
    coverImage: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
} | null;
// Variable: JOURNAL_INSIDER_SLUGS_QUERY
// Query: *[_type == "journalInsider" && defined(slug.current)]{ "slug": slug.current }
export type JOURNAL_INSIDER_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: JOURNAL_INSIDER_BY_SLUG_QUERY
// Query: *[_type == "journalInsider" && slug.current == $slug][0] {    _id,    title,    slug,    publishedAt,    "summary": coalesce(summary, description),    "publishedBy": coalesce(publishedBy, author),    content[],    "closingNote": coalesce(closingNote, curatorNote),    "coverImage": coverImage.asset-> {      _id,      url    }  }
export type JOURNAL_INSIDER_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  summary: string | null;
  publishedBy: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  closingNote: string | null;
  coverImage: {
    _id: string;
    url: string | null;
  } | null;
} | null;
// Variable: COLLECTION_BY_SLUG_QUERY
// Query: *[_type == "collection" && slug.current == $slug][0] {    _id,    name,    slug,    description,    "image": image.asset-> {      _id,      url    },    products[] -> {      _id,      name,      slug,      price,      priceINR,      badge,      notes,      description,      weight,      burnTime,      inStock,      "imageAlt": image.alt,      "image": image.asset-> {        _id,        url      }    }  }
export type COLLECTION_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    _id: string;
    url: string | null;
  } | null;
  products: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    price: number | null;
    priceINR: number | null;
    badge: string | null;
    notes: string | null;
    description: string | null;
    weight: string | null;
    burnTime: string | null;
    inStock: boolean | null;
    imageAlt: string | null;
    image: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
} | null;

// Source: ../sanity/queries_footer_navbar.ts
// Variable: NAVBAR_QUERY
// Query: *[_type == "navbar"][0] {    title,    announcementText,    navLinks[] {      label,      url    }  }
export type NAVBAR_QUERYResult = {
  title: string | null;
  announcementText: string | null;
  navLinks: Array<{
    label: string | null;
    url: string | null;
  }> | null;
} | null;
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0] {    title,    brandTagline,    copyrightText,    footerColumns[] {      columnTitle,      links[] {        label,        url      }    }  }
export type FOOTER_QUERYResult = {
  title: string | null;
  brandTagline: string | null;
  copyrightText: string | null;
  footerColumns: Array<{
    columnTitle: string | null;
    links: Array<{
      label: string | null;
      url: string | null;
    }> | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"page\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    pageType,\n    \n  \"sections\": sections[] {\n    ...,\n    _type,\n    _key,\n    \"backgroundImageUrl\": backgroundImage.asset->url,\n    \"imageUrl\": image.asset->url,\n    \"imageAlt\": coalesce(image.alt, backgroundImage.alt),\n    \"products\": products[]-> {\n      \n  _id,\n  name,\n  slug,\n  price,\n  priceINR,\n  badge,\n  notes,\n  description,\n  weight,\n  burnTime,\n  inStock,\n  \"image\": image.asset-> {\n    _id,\n    url\n  },\n  \"imageAlt\": image.alt\n\n    },\n    \"articles\": articles[]-> {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      \"summary\": coalesce(summary, description),\n      \"publishedBy\": coalesce(publishedBy, author),\n      coverImage\n    },\n    \"collections\": collections[]-> {\n      _id,\n      name,\n      slug,\n      description,\n      image\n    },\n    \"collection\": collection-> {\n      _id,\n      name,\n      slug,\n      \"products\": products[]-> {\n        \n  _id,\n  name,\n  slug,\n  price,\n  priceINR,\n  badge,\n  notes,\n  description,\n  weight,\n  burnTime,\n  inStock,\n  \"image\": image.asset-> {\n    _id,\n    url\n  },\n  \"imageAlt\": image.alt\n\n      }\n    }\n  }\n\n  }\n": PAGE_BY_SLUG_QUERYResult;
    "\n  *[_type == \"page\" && pageType == \"home\"][0] {\n    _id,\n    title,\n    slug,\n    pageType,\n    \n  \"sections\": sections[] {\n    ...,\n    _type,\n    _key,\n    \"backgroundImageUrl\": backgroundImage.asset->url,\n    \"imageUrl\": image.asset->url,\n    \"imageAlt\": coalesce(image.alt, backgroundImage.alt),\n    \"products\": products[]-> {\n      \n  _id,\n  name,\n  slug,\n  price,\n  priceINR,\n  badge,\n  notes,\n  description,\n  weight,\n  burnTime,\n  inStock,\n  \"image\": image.asset-> {\n    _id,\n    url\n  },\n  \"imageAlt\": image.alt\n\n    },\n    \"articles\": articles[]-> {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      \"summary\": coalesce(summary, description),\n      \"publishedBy\": coalesce(publishedBy, author),\n      coverImage\n    },\n    \"collections\": collections[]-> {\n      _id,\n      name,\n      slug,\n      description,\n      image\n    },\n    \"collection\": collection-> {\n      _id,\n      name,\n      slug,\n      \"products\": products[]-> {\n        \n  _id,\n  name,\n  slug,\n  price,\n  priceINR,\n  badge,\n  notes,\n  description,\n  weight,\n  burnTime,\n  inStock,\n  \"image\": image.asset-> {\n    _id,\n    url\n  },\n  \"imageAlt\": image.alt\n\n      }\n    }\n  }\n\n  }\n": HOME_PAGE_DOC_QUERYResult;
    "\n  *[_type == \"product\" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    price,\n    priceINR,\n    comparePrice,\n    badge,\n    notes,\n    description,\n    longDescription,\n    weight,\n    size,\n    sku,\n    burnTime,\n    accentNotes[],\n    inStock,\n    featured,\n    orderRank,\n    gallery[] {\n      asset-> {\n        _id,\n        url\n      },\n      caption\n    },\n    seo {\n      title,\n      description\n    },\n    \"image\": image.asset-> {\n      _id,\n      url\n    },\n    \"imageAlt\": image.alt,\n    collection -> {\n      name,\n      slug\n    },\n    insiderInfo -> {\n      title,\n      provenanceStory,\n      topNotes,\n      heartNotes,\n      baseNotes,\n      ingredientsList[],\n      gallery[] {\n        asset-> {\n          _id,\n          url\n        },\n        caption\n      }\n    }\n  }\n": PRODUCT_BY_SLUG_QUERYResult;
    "\n  *[_type == \"product\" && inStock == true] | order(orderRank asc, _createdAt asc) {\n    _id,\n    name,\n    slug,\n    price,\n    priceINR,\n    badge,\n    notes,\n    description,\n    weight,\n    burnTime,\n    \"image\": image.asset-> {\n      _id,\n      url\n    },\n    \"imageAlt\": image.alt,\n    inStock\n  }\n": PRODUCTS_LIST_QUERYResult;
    "\n  *[_type == \"journalArticle\"][0] {\n    title,\n    tagline,\n    \"articles\": articles[]-> {\n      \n  _id,\n  title,\n  slug,\n  publishedAt,\n  \"summary\": coalesce(summary, description),\n  \"publishedBy\": coalesce(publishedBy, author),\n  \"coverImage\": coverImage.asset-> {\n    _id,\n    url\n  }\n\n    }\n  }\n": JOURNAL_PAGE_QUERYResult;
    "\n  *[_type == \"journalInsider\" && defined(slug.current)]{ \"slug\": slug.current }\n": JOURNAL_INSIDER_SLUGS_QUERYResult;
    "\n  *[_type == \"journalInsider\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    \"summary\": coalesce(summary, description),\n    \"publishedBy\": coalesce(publishedBy, author),\n    content[],\n    \"closingNote\": coalesce(closingNote, curatorNote),\n    \"coverImage\": coverImage.asset-> {\n      _id,\n      url\n    }\n  }\n": JOURNAL_INSIDER_BY_SLUG_QUERYResult;
    "\n  *[_type == \"collection\" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    description,\n    \"image\": image.asset-> {\n      _id,\n      url\n    },\n    products[] -> {\n      _id,\n      name,\n      slug,\n      price,\n      priceINR,\n      badge,\n      notes,\n      description,\n      weight,\n      burnTime,\n      inStock,\n      \"imageAlt\": image.alt,\n      \"image\": image.asset-> {\n        _id,\n        url\n      }\n    }\n  }\n": COLLECTION_BY_SLUG_QUERYResult;
    "\n  *[_type == \"navbar\"][0] {\n    title,\n    announcementText,\n    navLinks[] {\n      label,\n      url\n    }\n  }\n": NAVBAR_QUERYResult;
    "\n  *[_type == \"footer\"][0] {\n    title,\n    brandTagline,\n    copyrightText,\n    footerColumns[] {\n      columnTitle,\n      links[] {\n        label,\n        url\n      }\n    }\n  }\n": FOOTER_QUERYResult;
  }
}
